name: Carmen On Cars
favicon: null
layout_spectrum: 0.5404
typography_spectrum: 0.13039701338857412
title: I will write something interesting here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25
  lightness: 0.7024093454238027
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
